import { Suspense } from "react";
import { redirect } from "next/navigation";
import type { Metadata } from "next";
import { ArrowLeft, Loader2 } from "lucide-react";
import { fetchTranscript, getVideoInfo } from "@/lib/youtube";
import TranscriptViewer from "@/components/TranscriptViewer";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

interface WatchPageProps {
  searchParams: Promise<{ v?: string; lang?: string; t?: string }>;
}

export async function generateMetadata({
  searchParams,
}: WatchPageProps): Promise<Metadata> {
  const { v: videoId } = await searchParams;

  if (!videoId) return {};

  return {
    title: `YouTube Transcript for Video ${videoId}`,
    description: `View, copy, and download the YouTube transcript for video ${videoId}. Generated by our free YouTube transcript generator — no sign-up required.`,
    alternates: {
      canonical: `/watch?v=${videoId}`,
    },
  };
}

export default async function WatchPage({ searchParams }: WatchPageProps) {
  const { v: videoId, lang: rawLang, t: startTimeRaw } = await searchParams;
  const lang = rawLang || "en";
  const startTime = Number(startTimeRaw) || 0;

  if (!videoId) {
    redirect("/");
  }

  let segments;
  let videoInfo;
  try {
    const result = await fetchTranscript(videoId, lang);
    segments = result.segments;
    videoInfo = await getVideoInfo(videoId);
  } catch (e) {
    return (
      <ErrorState
        message={
          e instanceof Error
            ? e.message
            : "Failed to fetch transcript. The video may not have captions available."
        }
        videoId={videoId}
      />
    );
  }

  if (!segments || segments.length === 0) {
    return (
      <ErrorState
        message="No transcript segments found for this video."
        videoId={videoId}
      />
    );
  }

  return (
    <div className="min-h-screen bg-background">
      <Header />

      <main className="flex-1">
        <div className="mx-auto max-w-4xl px-4 pt-6 sm:px-6">
          <a
            href="/"
            className="inline-flex items-center gap-1.5 text-sm text-muted transition-colors hover:text-foreground"
          >
            <ArrowLeft size={14} />
            Back to home
          </a>
        </div>

        <div className="mx-auto mt-4 max-w-4xl px-4 sm:px-6">
          <div className="aspect-video overflow-hidden rounded-xl bg-black shadow-lg">
            <iframe
              id="youtube-player"
              src={`https://www.youtube.com/embed/${videoId}?enablejsapi=1&origin=${process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000"}${startTime > 0 ? `&start=${startTime}` : ""}`}
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowFullScreen
              className="h-full w-full"
              title="YouTube video player"
            />
          </div>
        </div>

        <Suspense
          fallback={
            <div className="flex items-center justify-center py-20">
              <Loader2 className="animate-spin text-primary" size={24} />
            </div>
          }
        >
          <TranscriptViewer
            segments={segments}
            videoId={videoId}
            videoInfo={videoInfo}
            language={lang}
          />
        </Suspense>
      </main>
      <Footer />
    </div>
  );
}

function ErrorState({
  message,
  videoId,
}: {
  message: string;
  videoId: string;
}) {
  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="flex-1">
        <div className="mx-auto max-w-2xl px-4 pt-6 sm:px-6">
          <a
            href="/"
            className="inline-flex items-center gap-1.5 text-sm text-muted transition-colors hover:text-foreground"
          >
            <ArrowLeft size={14} />
            Back to home
          </a>
        </div>

        <div className="mx-auto mt-8 max-w-2xl px-4 sm:px-6">
          <div className="rounded-xl border border-border bg-surface p-8 text-center">
            <div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-full bg-red-50 text-red-500">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <circle cx="12" cy="12" r="10" />
                <line x1="12" x2="12" y1="8" y2="12" />
                <line x1="12" x2="12.01" y1="16" y2="16" />
              </svg>
            </div>
            <h2 className="text-lg font-semibold text-foreground">
              Transcript Not Available
            </h2>
            <p className="mt-2 text-sm leading-relaxed text-muted">
              {message}
            </p>
            <div className="mt-4 aspect-video overflow-hidden rounded-xl bg-black shadow-lg">
              <iframe
                src={`https://www.youtube.com/embed/${videoId}`}
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowFullScreen
                className="h-full w-full"
                title="YouTube video player"
              />
            </div>
            <a
              href="/"
              className="mt-6 inline-flex items-center gap-2 rounded-lg bg-primary px-5 py-2.5 text-sm font-semibold text-white transition-colors hover:bg-primary-dark"
            >
              Try Another Video
            </a>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
