import { jsPDF } from "jspdf";
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  Header,
  Footer,
  AlignmentType,
  HeadingLevel,
} from "docx";
import { saveAs } from "file-saver";
import type { TranscriptSegment } from "./youtube";

function formatTime(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return `${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}`;
}

function toSrtTime(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = seconds % 60;
  const ms = Math.floor((s - Math.floor(s)) * 1000);
  return `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}:${String(Math.floor(s)).padStart(2, "0")},${String(ms).padStart(3, "0")}`;
}

export function exportTxt(
  segments: TranscriptSegment[],
  videoId: string
) {
  const content = segments
    .map((s) => `${formatTime(s.offset)}\n${s.text}`)
    .join("\n\n");
  downloadBlob(content, "text/plain", `transcript-${videoId}.txt`);
}

export function exportSrt(
  segments: TranscriptSegment[],
  videoId: string
) {
  const content = segments
    .map((s, i) => {
      const end = s.offset + s.duration;
      return `${i + 1}\n${toSrtTime(s.offset)} --> ${toSrtTime(end)}\n${s.text}`;
    })
    .join("\n\n");
  downloadBlob(content, "text/plain", `transcript-${videoId}.srt`);
}

export function exportVtt(
  segments: TranscriptSegment[],
  videoId: string
) {
  const content =
    `WEBVTT\n\n` +
    segments
      .map((s) => {
        const end = s.offset + s.duration;
        return `${toSrtTime(s.offset)} --> ${toSrtTime(end)}\n${s.text}`;
      })
      .join("\n\n");
  downloadBlob(content, "text/vtt", `transcript-${videoId}.vtt`);
}

export function exportPdf(
  segments: TranscriptSegment[],
  videoId: string,
  title: string
) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(title || `YouTube Transcript — ${videoId}`, margin, 25);

  // Subtitle
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(
    `Generated by YouTube Transcripts | ${segments.length} segments | ${new Date().toLocaleDateString()}`,
    margin,
    33
  );

  doc.setTextColor(0);
  let y = 45;

  segments.forEach((seg) => {
    // Timestamp
    const timeStr = formatTime(seg.offset);

    // Check if we need a new page
    if (y > 270) {
      doc.addPage();
      y = 25;
    }

    // Timestamp in bold, primary color
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(79, 70, 229);
    doc.text(timeStr, margin, y);
    y += 5;

    // Text
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(30);

    // Word wrap the text
    const lines = doc.splitTextToSize(seg.text, maxWidth);
    lines.forEach((line: string) => {
      if (y > 280) {
        doc.addPage();
        y = 25;
      }
      doc.text(line, margin, y);
      y += 5;
    });

    y += 3;
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(180);
    doc.text(
      `YouTube Transcripts — Free Transcript Generator | Page ${i} of ${pageCount}`,
      margin,
      290
    );
  }

  doc.save(`transcript-${videoId}.pdf`);
}

export async function exportDocx(
  segments: TranscriptSegment[],
  videoId: string
) {
  const children: Paragraph[] = [];

  // Title
  children.push(
    new Paragraph({
      text: `YouTube Transcript — ${videoId}`,
      heading: HeadingLevel.TITLE,
      spacing: { after: 200 },
    })
  );

  children.push(
    new Paragraph({
      text: `Generated by YouTube Transcripts | ${segments.length} segments`,
      spacing: { after: 400 },
    })
  );

  segments.forEach((seg) => {
    const timeStr = formatTime(seg.offset);

    children.push(
      new Paragraph({
        spacing: { before: 200 },
        children: [
          new TextRun({
            text: timeStr,
            bold: true,
            color: "4F46E5",
            size: 18,
          }),
        ],
      })
    );

    children.push(
      new Paragraph({
        spacing: { after: 200 },
        children: [
          new TextRun({
            text: seg.text,
            size: 20,
          }),
        ],
      })
    );
  });

  const doc = new Document({
    title: `YouTube Transcript — ${videoId}`,
    description: "Generated by YouTube Transcripts",
    styles: {
      default: {
        document: {
          run: {
            font: "Arial",
            size: 20,
          },
        },
      },
    },
    sections: [
      {
        properties: {},
        headers: {
          default: new Header({
            children: [
              new Paragraph({
                text: "YouTube Transcripts — Free Transcript Generator",
                alignment: AlignmentType.CENTER,
              }),
            ],
          }),
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                text: "Generated by YouTube Transcripts",
                alignment: AlignmentType.CENTER,
              }),
            ],
          }),
        },
        children,
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, `transcript-${videoId}.docx`);
}

function downloadBlob(
  content: string,
  mime: string,
  filename: string
) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
