import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { getSharedTranscript } from "@/lib/share";
import SharedTranscriptView from "./SharedTranscriptView";

interface SharePageProps {
  params: Promise<{ id: string }>;
  searchParams: Promise<{ t?: string }>;
}

export async function generateMetadata({
  params,
}: SharePageProps): Promise<Metadata> {
  const { id } = await params;
  const data = await getSharedTranscript(id);

  if (!data) return {};

  return {
    title: `Shared Transcript — YouTube Video ${data.videoId}`,
    description: `View a shared YouTube transcript for video ${data.videoId}. Generated by YouTube Transcripts.`,
    alternates: {
      canonical: `/share/${id}`,
    },
  };
}

export default async function SharePage({ params, searchParams }: SharePageProps) {
  const { id } = await params;
  const { t } = await searchParams;
  const data = await getSharedTranscript(id);

  if (!data) {
    notFound();
  }

  return <SharedTranscriptView data={data} startTime={Number(t) || 0} />;
}
