import Header from "@/components/Header";
import Hero from "@/components/Hero";
import FeatureCards from "@/components/FeatureCards";
import HowToSection from "@/components/HowToSection";
import FAQ from "@/components/FAQ";
import Footer from "@/components/Footer";
import { FaqJsonLd } from "@/components/JsonLd";

const faqData = [
  {
    q: "What is a YouTube transcript generator?",
    a: "A YouTube transcript generator is a tool that converts spoken content from YouTube videos into written text. Our free YouTube transcript generator automatically extracts and formats transcripts from any YouTube video, complete with timestamps, so you can read, copy, or download the content in seconds.",
  },
  {
    q: "How do I generate a YouTube transcript?",
    a: "Simply paste the YouTube video URL into our transcript generator and click 'Generate Transcript'. Our tool instantly extracts the transcript from YouTube's captions or auto-generated subtitles and displays it with clickable timestamps.",
  },
  {
    q: "Is this YouTube transcript generator free?",
    a: "Yes, our YouTube transcript generator is free. Anonymous users can generate up to 3 transcripts per day, and signed-in users can generate up to 100 per day.",
  },
  {
    q: "Does the transcript include timestamps?",
    a: "Yes! Every transcript generated by our tool includes precise timestamps for each segment. You can click any timestamp to jump directly to that moment in the YouTube video.",
  },
  {
    q: "Can I download the YouTube transcript?",
    a: "Yes, you can download your YouTube transcript in TXT, SRT, or VTT format. You can also copy the transcript to your clipboard with or without timestamps.",
  },
  {
    q: "Can I get an AI summary of the YouTube video?",
    a: "Yes! Along with the full transcript, you can generate an AI-powered summary of any YouTube video. Choose between brief, detailed, or bullet-point formats.",
  },
];

export default function Home() {
  return (
    <>
      <Header />
      <FaqJsonLd faqs={faqData} />
      <main className="flex-1">
        <Hero />
        <FeatureCards />
        <HowToSection />
        <FAQ />
      </main>
      <Footer />
    </>
  );
}
