"use client";

import { useState } from "react";
import { ChevronDown } from "lucide-react";
import { cn } from "@/lib/utils";

const faqs = [
  {
    q: "What is a YouTube transcript generator?",
    a: "A YouTube transcript generator is a tool that converts spoken content from YouTube videos into written text. Our free YouTube transcript generator automatically extracts and formats transcripts from any YouTube video, complete with timestamps, so you can read, copy, or download the content in seconds.",
  },
  {
    q: "How do I generate a YouTube transcript?",
    a: "Simply paste the YouTube video URL into our transcript generator above and click 'Generate Transcript'. Our tool instantly extracts the transcript from YouTube's captions or auto-generated subtitles and displays it with clickable timestamps. You can then copy the text or download it in TXT, SRT, or VTT format.",
  },
  {
    q: "Is this YouTube transcript generator free?",
    a: "Yes, our YouTube transcript generator is completely free with no hidden fees, no sign-up required, and no usage limits. You can generate as many transcripts as you need, for any YouTube video.",
  },
  {
    q: "Does the transcript include timestamps?",
    a: "Yes! Every transcript generated by our tool includes precise timestamps for each segment. You can click any timestamp to jump directly to that moment in the YouTube video, making it easy to navigate and review specific parts.",
  },
  {
    q: "Can I download the YouTube transcript?",
    a: "Yes, you can download your YouTube transcript in multiple formats: TXT for plain text reading, SRT for subtitle files compatible with video players, and VTT for web-based video captions. You can also copy the transcript to your clipboard with or without timestamps.",
  },
  {
    q: "What video formats does the transcript generator support?",
    a: "Our YouTube transcript generator works with all YouTube video formats including standard YouTube URLs (youtube.com/watch?v=), shortened URLs (youtu.be/), YouTube Shorts, and embedded video URLs. You can also paste just the 11-character video ID.",
  },
  {
    q: "How long does it take to generate a transcript?",
    a: "Most YouTube transcripts are generated in just a few seconds. The time depends on the video length and whether YouTube has captions available. Videos with existing captions are processed almost instantly.",
  },
  {
    q: "Can I get an AI summary of the YouTube video?",
    a: "Yes! Along with the full transcript, you can generate an AI-powered summary of any YouTube video. Choose between brief, detailed, or bullet-point formats to quickly extract key topics, ideas, and takeaways without watching the entire video.",
  },
  {
    q: "What can I use a YouTube transcript for?",
    a: "YouTube transcripts are useful for content repurposing, SEO optimization, creating subtitles and captions, research and note-taking, language learning, accessibility for deaf or hard-of-hearing viewers, quoting video content in articles, and quickly reviewing video content without watching the full length.",
  },
  {
    q: "Does the tool work on mobile devices?",
    a: "Yes, our YouTube transcript generator works on any device with a browser — Windows, Mac, Android, iPhone, and tablets. Simply visit the website, paste a YouTube URL, and generate a transcript instantly.",
  },
];

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  return (
    <section
      id="faq"
      className="border-b border-border py-20"
      itemScope
      itemType="https://schema.org/FAQPage"
    >
      <div className="mx-auto max-w-3xl px-4 sm:px-6">
        <div className="text-center">
          <h2 className="text-3xl font-bold tracking-tight text-foreground">
            Frequently Asked Questions
          </h2>
          <p className="mt-4 text-muted">
            Everything you need to know about using our{" "}
            <strong>YouTube transcript generator</strong>.
          </p>
        </div>

        <div className="mt-10 divide-y divide-border">
          {faqs.map((faq, i) => (
            <div
              key={i}
              itemScope
              itemProp="mainEntity"
              itemType="https://schema.org/Question"
            >
              <button
                onClick={() => setOpenIndex(openIndex === i ? null : i)}
                className="flex w-full items-center justify-between gap-4 py-4 text-left transition-colors hover:text-primary"
              >
                <span
                  className="text-sm font-medium"
                  itemProp="name"
                >
                  {faq.q}
                </span>
                <ChevronDown
                  size={16}
                  className={cn(
                    "shrink-0 text-muted transition-transform duration-200",
                    openIndex === i && "rotate-180"
                  )}
                />
              </button>
              {openIndex === i && (
                <div
                  className="pb-4 text-sm leading-relaxed text-muted"
                  itemScope
                  itemProp="acceptedAnswer"
                  itemType="https://schema.org/Answer"
                >
                  <div itemProp="text">{faq.a}</div>
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
